### ISSUE TITLE
Check moviepy is installed before starting.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [yownas/seed_travel#10]
After doing a fresh install of SD I forgot to add the moviepy line to the requirements versions. There is no warning of this until after it has created all of the images and tries to create the video. It would be nice if it was checked earlier on, to avoid the creation of images that aren't used.

**Comment by yownas** [comment]
At work at the moment. But I'll fix this when I get home.
I'm thinking of adding a check when you click Generate that will fail if you have "Save results as video" enabled but haven't installed the module.
Alternatively, write a warning and then turn off "Save results as video". But I think that might annoying since you would still end up with pictures and no video.

**Comment by yownas** [comment]
Fixed in

**Comment by yownas** [comment]
Fixed in https://github.com/yownas/seed_travel/commit/3affa62184b70f6a3b1bb4ce191b0c1b3105e253

Decided to just not generate anything if "Save result as video" is checked but moviepy is missing. Then the user can decide if they want to generate images anyway, or go back in time and install moviepy before starting the webui.

(I'll accept any PR that solves the latter.)
