### ISSUE TITLE
combining seed travel generated images with a frame interpolation engine for smooth video output

### ISSUE THREAD

**Issue by vladmandic** [yownas/seed_travel#35]
I just did a quick prototype using only couple of frames generated using your nice seed travel script and interpolated 50x frames using ml video interpolation, result is not bad at all. perhaps worth considering integrating into all-in-one extension?

code and example at: <https://github.com/vladmandic/rife>

**Comment by yownas** [comment]
This would be great. I've seen some animations where people used RIFE to smooth things out and it looks really good.

Hopefully I'll find some times to look into this soon™.

**Comment by yownas** [comment]
Wow! I finally got some time to sit down yesterday and test things. It works great! 
There is still a bit of code/ui cleanup to do before I can push the changes.

**Comment by yownas** [comment]
Pushed now. :)

**Comment by vladmandic** [comment]
very nice!

one issue - if rife is used, it creates **both** normal and interpolated mp4 in output folder.

btw, can you rename `rife pass` - the fact that its `rife` is not relevant to end-user, its simply `interpolated frames`

**Comment by yownas** [comment]
Getting both video-files is intentional. Partly by laziness but mostly because I didn't want to clutter the UI with even more choices. I wanted to keep things as simple as possible, and by now it it almost reaching deforum-levels of sliders and input fields. :) Plus you get the original video and can compare results or work on it further if you didn't like the result. So there is some logic behind keeping it, even if it looks a bit odd.

Naming things is hard, there is the same issue with the SSIM fields. It makes sense if you know what SSIM or RIFE is. Calling it `interpolation <something>` risks getting it confused with the interpolation of the seeds, which probably also should have another name... I saw your other ticket about the length of the names, and I agree, that needs fixing. I'll see if I can come up with something simple and more intuitive that the current setup.
