### ISSUE TITLE
[User Submission] seed travel with controlnet!

### ISSUE THREAD

**Issue by ClashSAN** [yownas/seed_travel#38]
https://user-images.githubusercontent.com/98228077/220402727-524fa679-3bd7-47e9-96c0-c98b876c13a1.mp4

```
an sks kirby protagonist, colorful, rainbow
Negative prompt:
Sampling method: DPMS 2M++ Karras; Sampling Steps: 10; CFG Scale: 7
Seed: 1,2,3
Script: seed travel; Controlnet: hed preprocessor, hed model, Image: https://user-images.githubusercontent.com/98228077/220402306-5b110c6e-158d-4b98-825a-d3716b8e1dc3.jpg
Steps: 100; FPS: 30
```

**Comment by AladdinFPV** [comment]
> Added. :)

Hiii, I tried using seed travel with control net and the results are amazing, for a single image. 

But is it possible to use it with Batch? I tried to use with batch img2img but doesn't seem to be working, getting an error "FileNotFoundError: [Errno 2] No such file or directory: 'outputs/img2img-images\\travels\\00005\\seed_travel-info-00005.txt'" Seems that seed travel cannot create an output folder in Travels folder while using Batch, and Output directory for batch is ignored, and not sure if it's reading Input.

![image](https://user-images.githubusercontent.com/130452224/234537698-5a07798b-1899-479a-9a09-62676faa58d1.png)

End goal is to generate style for my frames as consistent as possible and seed travel seems to have the best change in outcome so far for single image since it's working between only two seeds. I'm hoping I can change style for 50 different images with the same seed (Input images are really similar to each other just simple movement) 

Thanks
