### ISSUE TITLE
suggestion to cleanup ui

### ISSUE THREAD

**Issue by vladmandic** [yownas/seed_travel#44]
and any chance you can remove all ui text in `(...)` and implement as on-mouse-hove hints?
as-it-is, it's creating a very messy ui look (especially on lower widths when everything starts to wrap due to string lengths).

also, i think at least half of settings can be considered as *"advanced"* and not modified regularly - maybe they can be moved into additional gradio harmonica element that is collapsed by default.

see below for example:
![image](https://user-images.githubusercontent.com/57876960/226189001-d513c473-2bc1-4546-b453-b3ba684c5ee1.png)

**Comment by yownas** [comment]
Yes, that needs fixing. I'll look into the harmonica element again, I did it once in the beginning but never got it to work. But I have a bit more experience with gradio now than I had back then, so it might actually work this time. :)

**Comment by yownas** [comment]
Trying to find documentation for the "harmonica" block worked took longer than I expected...annoying since I know I've looked at it before and even tested it...anyway... after a lot of googling I added a "accordion" block and made the text shorter. :)

Now I have a place to hide new pointless buttons.

I skipped the mouse-over thing, I tried to copy code from another extension but it didn't work and "FPS" got it's mouse-over from the deforum extension.
